<?php

use Illuminate\Database\Seeder;

class DatabaseSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('estado_civil')->insert([
            ['descricao' => 'Solteiro'],
            ['descricao' => 'Casado'],
            ['descricao' => 'Divorciado'],
            ['descricao' => 'Viúvo'],
            ['descricao' => 'União Estável'],
        ]);
        DB::table('pais')->insert([			
        	['nome'=>'Afeganistão', 'gentilico'=>'afegãne', 'sigla'=>'AFG', 'sigla_web'=>'AF'],
			['nome'=>'África do Sul', 'gentilico'=>'sul-africana', 'sigla'=>'ZAF', 'sigla_web'=>'ZA'],
			['nome'=>'Albânia', 'gentilico'=>'albanesa', 'sigla'=>'ALB', 'sigla_web'=>'AL'],
			['nome'=>'Alemanha', 'gentilico'=>'alemã', 'sigla'=>'DEU', 'sigla_web'=>'DE'],
			['nome'=>'Andorra', 'gentilico'=>'andorrana', 'sigla'=>'AND', 'sigla_web'=>'AD'],
			['nome'=>'Angola', 'gentilico'=>'angolana', 'sigla'=>'AGO', 'sigla_web'=>'AO'],
			['nome'=>'Anguilla', 'gentilico'=>'anguillana', 'sigla'=>'AIA', 'sigla_web'=>'AI'],
			['nome'=>'Antártida', 'gentilico'=>'de antártida', 'sigla'=>'ATA', 'sigla_web'=>'AQ'],
			['nome'=>'Antígua e Barbuda', 'gentilico'=>'antiguana', 'sigla'=>'ATG', 'sigla_web'=>'AG'],
			['nome'=>'Antilhas Holandesas', 'gentilico'=>'', 'sigla'=>'ANT', 'sigla_web'=>'AN'],
			['nome'=>'Arábia Saudita', 'gentilico'=>'saudita', 'sigla'=>'SAU', 'sigla_web'=>'SA'],
			['nome'=>'Argélia', 'gentilico'=>'argelina', 'sigla'=>'DZA', 'sigla_web'=>'DZ'],
			['nome'=>'Argentina', 'gentilico'=>'argentina', 'sigla'=>'ARG', 'sigla_web'=>'AR'],
			['nome'=>'Armênia', 'gentilico'=>'armênia', 'sigla'=>'ARM', 'sigla_web'=>'AM'],
			['nome'=>'Aruba', 'gentilico'=>'arubana', 'sigla'=>'ABW', 'sigla_web'=>'AW'],
			['nome'=>'Austrália', 'gentilico'=>'australiana', 'sigla'=>'AUS', 'sigla_web'=>'AU'],
			['nome'=>'Áustria', 'gentilico'=>'austríaca', 'sigla'=>'AUT', 'sigla_web'=>'AT'],
			['nome'=>'Azerbaijão', 'gentilico'=>'azerbaijano', 'sigla'=>'AZE', 'sigla_web'=>'AZ'],
			['nome'=>'Bahamas', 'gentilico'=>'bahamense', 'sigla'=>'BHS', 'sigla_web'=>'BS'],
			['nome'=>'Bahrein', 'gentilico'=>'barenita', 'sigla'=>'BHR', 'sigla_web'=>'BH'],
			['nome'=>'Bangladesh', 'gentilico'=>'bengali', 'sigla'=>'BGD', 'sigla_web'=>'BD'],
			['nome'=>'Barbados', 'gentilico'=>'barbadiana', 'sigla'=>'BRB', 'sigla_web'=>'BB'],
			['nome'=>'Belarus', 'gentilico'=>'bielo-russa', 'sigla'=>'BLR', 'sigla_web'=>'BY'],
			['nome'=>'Bélgica', 'gentilico'=>'belga', 'sigla'=>'BEL', 'sigla_web'=>'BE'],
			['nome'=>'Belize', 'gentilico'=>'belizenha', 'sigla'=>'BLZ', 'sigla_web'=>'BZ'],
			['nome'=>'Benin', 'gentilico'=>'beninense', 'sigla'=>'BEN', 'sigla_web'=>'BJ'],
			['nome'=>'Bermudas', 'gentilico'=>'bermudiana', 'sigla'=>'BMU', 'sigla_web'=>'BM'],
			['nome'=>'Bolívia', 'gentilico'=>'boliviana', 'sigla'=>'BOL', 'sigla_web'=>'BO'],
			['nome'=>'Bósnia-Herzegóvina', 'gentilico'=>'bósnia', 'sigla'=>'BIH', 'sigla_web'=>'BA'],
			['nome'=>'Botsuana', 'gentilico'=>'betchuana', 'sigla'=>'BWA', 'sigla_web'=>'BW'],
			['nome'=>'Brasil', 'gentilico'=>'brasileira', 'sigla'=>'BRA', 'sigla_web'=>'BR'],
			['nome'=>'Brunei', 'gentilico'=>'bruneiana', 'sigla'=>'BRN', 'sigla_web'=>'BN'],
			['nome'=>'Bulgária', 'gentilico'=>'búlgara', 'sigla'=>'BGR', 'sigla_web'=>'BG'],
			['nome'=>'Burkina Fasso', 'gentilico'=>'burquinês', 'sigla'=>'BFA', 'sigla_web'=>'BF'],
			['nome'=>'Burundi', 'gentilico'=>'burundinesa', 'sigla'=>'BDI', 'sigla_web'=>'BI'],
			['nome'=>'Butão', 'gentilico'=>'butanesa', 'sigla'=>'BTN', 'sigla_web'=>'BT'],
			['nome'=>'Cabo Verde', 'gentilico'=>'cabo-verdiana', 'sigla'=>'CPV', 'sigla_web'=>'CV'],
			['nome'=>'Camarões', 'gentilico'=>'camaronesa', 'sigla'=>'CMR', 'sigla_web'=>'CM'],
			['nome'=>'Camboja', 'gentilico'=>'cambojana', 'sigla'=>'KHM', 'sigla_web'=>'KH'],
			['nome'=>'Canadá', 'gentilico'=>'canadense', 'sigla'=>'CAN', 'sigla_web'=>'CA'],
			['nome'=>'Cazaquistão', 'gentilico'=>'cazaque', 'sigla'=>'KAZ', 'sigla_web'=>'KA'],
			['nome'=>'Chade', 'gentilico'=>'turquesa', 'sigla'=>'TCD', 'sigla_web'=>'TD'],
			['nome'=>'Chile', 'gentilico'=>'chilena', 'sigla'=>'CHL', 'sigla_web'=>'CH'],
			['nome'=>'China', 'gentilico'=>'chinesa', 'sigla'=>'CHN', 'sigla_web'=>'CH'],
			['nome'=>'Chipre', 'gentilico'=>'cipriota', 'sigla'=>'196', 'sigla_web'=>'CY'],
			['nome'=>'Cingapura', 'gentilico'=>'cingapuriana', 'sigla'=>'SGP', 'sigla_web'=>'SG'],
			['nome'=>'Colômbia', 'gentilico'=>'colombiana', 'sigla'=>'COL', 'sigla_web'=>'CO'],
			['nome'=>'Congo', 'gentilico'=>'congolesa', 'sigla'=>'COG', 'sigla_web'=>'CG'],
			['nome'=>'Coréia do Norte', 'gentilico'=>'norte coreana', 'sigla'=>'PRK', 'sigla_web'=>'KP'],
			['nome'=>'Coréia do Sul', 'gentilico'=>'sul coreana', 'sigla'=>'KOR', 'sigla_web'=>'KR'],
			['nome'=>'Costa do Marfim', 'gentilico'=>'marfinense', 'sigla'=>'CIV', 'sigla_web'=>'CI'],
			['nome'=>'Costa Rica', 'gentilico'=>'costarriquenha', 'sigla'=>'CRI', 'sigla_web'=>'CR'],
			['nome'=>'Croácia', 'gentilico'=>'croata', 'sigla'=>'HRV', 'sigla_web'=>'HR'],
			['nome'=>'Cuba', 'gentilico'=>'cubana', 'sigla'=>'CUB', 'sigla_web'=>'CU'],
			['nome'=>'Dinamarca', 'gentilico'=>'dinamarquesa', 'sigla'=>'DNK', 'sigla_web'=>'DN'],
			['nome'=>'Djibuti', 'gentilico'=>'djibutiana', 'sigla'=>'DJI', 'sigla_web'=>'DJ'],
			['nome'=>'Dominica', 'gentilico'=>'dominiquense', 'sigla'=>'DMA', 'sigla_web'=>'DM'],
			['nome'=>'Egitp', 'gentilico'=>'egípcia', 'sigla'=>'EGY', 'sigla_web'=>'EG'],
			['nome'=>'El Salvador', 'gentilico'=>'salvadorenha', 'sigla'=>'SLV', 'sigla_web'=>'SV'],
			['nome'=>'Emirados Árabes Unidos', 'gentilico'=>'árabe', 'sigla'=>'ARE', 'sigla_web'=>'AE'],
			['nome'=>'Equador', 'gentilico'=>'equatoriana', 'sigla'=>'ECU', 'sigla_web'=>'EC'],
			['nome'=>'Eritréia', 'gentilico'=>'eritréia', 'sigla'=>'ERI', 'sigla_web'=>'ER'],
			['nome'=>'Eslováquia', 'gentilico'=>'eslovaca', 'sigla'=>'SVK', 'sigla_web'=>'SK'],
			['nome'=>'Eslovênia', 'gentilico'=>'eslovena', 'sigla'=>'SVN', 'sigla_web'=>'SI'],
			['nome'=>'Espanha', 'gentilico'=>'espanhola', 'sigla'=>'ESP', 'sigla_web'=>'ES'],
			['nome'=>'Estados Unidos da América', 'gentilico'=>'norte-americana', 'sigla'=>'USA', 'sigla_web'=>'US'],
			['nome'=>'Estônia', 'gentilico'=>'estoniana', 'sigla'=>'EST', 'sigla_web'=>'EE'],
			['nome'=>'Etiópia', 'gentilico'=>'etíope', 'sigla'=>'ETH', 'sigla_web'=>'ET'],
			['nome'=>'Fiji', 'gentilico'=>'fijiana', 'sigla'=>'FJI', 'sigla_web'=>'FJ'],
			['nome'=>'Filipinas', 'gentilico'=>'filipina', 'sigla'=>'PHL', 'sigla_web'=>'PH'],
			['nome'=>'Finlândia', 'gentilico'=>'finlandesa', 'sigla'=>'FIN', 'sigla_web'=>'FI'],
			['nome'=>'França', 'gentilico'=>'francesa', 'sigla'=>'FRA', 'sigla_web'=>'FR'],
			['nome'=>'Gabão', 'gentilico'=>'gabonesa', 'sigla'=>'GAB', 'sigla_web'=>'GA'],
			['nome'=>'Gâmbia', 'gentilico'=>'gambiana', 'sigla'=>'GMB', 'sigla_web'=>'GM'],
			['nome'=>'Gana', 'gentilico'=>'ganense', 'sigla'=>'GHA', 'sigla_web'=>'GH'],
			['nome'=>'Geórgia', 'gentilico'=>'georgiana', 'sigla'=>'GEO', 'sigla_web'=>'GE'],
			['nome'=>'Gibraltar', 'gentilico'=>'gibraltariana', 'sigla'=>'GIB', 'sigla_web'=>'GI'],
			['nome'=>'Grã-Bretanha (Reino Unido, UK)', 'gentilico'=>'inglesa', 'sigla'=>'GBR', 'sigla_web'=>'GB'],
			['nome'=>'Granada', 'gentilico'=>'granadina', 'sigla'=>'GRD', 'sigla_web'=>'GD'],
			['nome'=>'Grécia', 'gentilico'=>'grega', 'sigla'=>'GRC', 'sigla_web'=>'GR'],
			['nome'=>'Groelândia', 'gentilico'=>'groenlandesa', 'sigla'=>'GRL', 'sigla_web'=>'GL'],
			['nome'=>'Guadalupe', 'gentilico'=>'guadalupense', 'sigla'=>'GLP', 'sigla_web'=>'GP'],
			['nome'=>'Guam (Território dos Estados Unidos)', 'gentilico'=>'guamês', 'sigla'=>'GUM', 'sigla_web'=>'GU'],
			['nome'=>'Guatemala', 'gentilico'=>'guatemalteca', 'sigla'=>'GTM', 'sigla_web'=>'GT'],
			['nome'=>'Guernsey', 'gentilico'=>'', 'sigla'=>'GGY', 'sigla_web'=>'G'],
			['nome'=>'Guiana', 'gentilico'=>'guianense', 'sigla'=>'GUY', 'sigla_web'=>'GY'],
			['nome'=>'Guiana Francesa', 'gentilico'=>'franco-guianense', 'sigla'=>'GUF', 'sigla_web'=>'GF'],
			['nome'=>'Guiné', 'gentilico'=>'guinéu-equatoriano ou equatoguineana', 'sigla'=>'GIN', 'sigla_web'=>'GN'],
			['nome'=>'Guiné Equatorial', 'gentilico'=>'guinéu-equatoriano', 'sigla'=>'GNQ', 'sigla_web'=>'GQ'],
			['nome'=>'Guiné-Bissau', 'gentilico'=>'guineense', 'sigla'=>'GNB', 'sigla_web'=>'GW'],
			['nome'=>'Haiti', 'gentilico'=>'haitiana', 'sigla'=>'HTI', 'sigla_web'=>'HT'],
			['nome'=>'Holanda', 'gentilico'=>'holandês', 'sigla'=>'NLD', 'sigla_web'=>'NL'],
			['nome'=>'Honduras', 'gentilico'=>'hondurenha', 'sigla'=>'HND', 'sigla_web'=>'HN'],
			['nome'=>'Hong Kong', 'gentilico'=>'hong-konguiana ou chinesa', 'sigla'=>'HKG', 'sigla_web'=>'HK'],
			['nome'=>'Hungria', 'gentilico'=>'húngara', 'sigla'=>'HUN', 'sigla_web'=>'HU'],
			['nome'=>'Iêmen', 'gentilico'=>'iemenita', 'sigla'=>'YEM', 'sigla_web'=>'YE'],
			['nome'=>'Ilha Bouvet (Território da Noruega)', 'gentilico'=>'da ilha bouvet', 'sigla'=>'BVT', 'sigla_web'=>'BV'],
			['nome'=>'Ilha do Homem', 'gentilico'=>'manês', 'sigla'=>'IMN', 'sigla_web'=>'IM'],
			['nome'=>'Ilha Natal', 'gentilico'=>'natalense', 'sigla'=>'CXR', 'sigla_web'=>'CX'],
			['nome'=>'Ilha Pitcairn', 'gentilico'=>'pitcairnense', 'sigla'=>'PCN', 'sigla_web'=>'PN'],
			['nome'=>'Ilha Reunião', 'gentilico'=>'reunionense', 'sigla'=>'REU', 'sigla_web'=>'RE'],
			['nome'=>'Ilhas Aland', 'gentilico'=>'alandês', 'sigla'=>'ALA', 'sigla_web'=>'AX'],
			['nome'=>'Ilhas Cayman', 'gentilico'=>'caimanês', 'sigla'=>'CYM', 'sigla_web'=>'KY'],
			['nome'=>'Ilhas Cocos', 'gentilico'=>'coquense', 'sigla'=>'CCK', 'sigla_web'=>'CC'],
			['nome'=>'Ilhas Comores', 'gentilico'=>'comorense', 'sigla'=>'COM', 'sigla_web'=>'KM'],
			['nome'=>'Ilhas Cook', 'gentilico'=>'cookense', 'sigla'=>'COK', 'sigla_web'=>'CK'],
			['nome'=>'Ilhas Faroes', 'gentilico'=>'faroense', 'sigla'=>'FRO', 'sigla_web'=>'FO'],
			['nome'=>'Ilhas Falkland (Malvinas)', 'gentilico'=>'malvinense', 'sigla'=>'FLK', 'sigla_web'=>'FK'],
			['nome'=>'Ilhas Geórgia do Sul e Sandwich do Sul', 'gentilico'=>'das ilhas geórgia do sul e sandwich do sul', 'sigla'=>'SGS', 'sigla_web'=>'GS'],
			['nome'=>'Ilhas Heard e McDonald (Território da Austrália)', 'gentilico'=>'das ilhas heard e mcdonald', 'sigla'=>'HMD', 'sigla_web'=>'HM'],
			['nome'=>'Ilhas Marianas do Norte', 'gentilico'=>'norte-marianense', 'sigla'=>'MNP', 'sigla_web'=>'MP'],
			['nome'=>'Ilhas Marshall', 'gentilico'=>'marshallino', 'sigla'=>'MHL', 'sigla_web'=>'MH'],
			['nome'=>'Ilhas Menores dos Estados Unidos', 'gentilico'=>'das ilhas menores afastadas', 'sigla'=>'UMI', 'sigla_web'=>'UM'],
			['nome'=>'Ilhas Norfolk', 'gentilico'=>'norfolquino', 'sigla'=>'NFK', 'sigla_web'=>'NF'],
			['nome'=>'Ilhas Seychelles', 'gentilico'=>'seichelense', 'sigla'=>'SYC', 'sigla_web'=>'SC'],
			['nome'=>'Ilhas Solomão', 'gentilico'=>'salomônico', 'sigla'=>'SLB', 'sigla_web'=>'SB'],
			['nome'=>'Ilhas Svalbard e Jan Mayen', 'gentilico'=>'svalbardense', 'sigla'=>'SJM', 'sigla_web'=>'SJ'],
			['nome'=>'Ilhas Tokelau', 'gentilico'=>'toquelauano', 'sigla'=>'TKL', 'sigla_web'=>'TK'],
			['nome'=>'Ilhas Turks e Caicos', 'gentilico'=>'turquês', 'sigla'=>'TCA', 'sigla_web'=>'TC'],
			['nome'=>'Ilhas Virgens (Estados Unidos)', 'gentilico'=>'virginense', 'sigla'=>'VIR', 'sigla_web'=>'VI'],
			['nome'=>'Ilhas Virgens (Inglaterra)', 'gentilico'=>'virginense', 'sigla'=>'VGB', 'sigla_web'=>'VG'],
			['nome'=>'Ilhas Wallis e Futuna', 'gentilico'=>'wallis-futunense', 'sigla'=>'WLF', 'sigla_web'=>'WF'],
			['nome'=>'índia', 'gentilico'=>'indiano', 'sigla'=>'IND', 'sigla_web'=>'IN'],
			['nome'=>'Indonésia', 'gentilico'=>'indonésia', 'sigla'=>'IDN', 'sigla_web'=>'ID'],
			['nome'=>'Irã', 'gentilico'=>'iraniano', 'sigla'=>'IRN', 'sigla_web'=>'IR'],
			['nome'=>'Iraque', 'gentilico'=>'iraquiana', 'sigla'=>'IRQ', 'sigla_web'=>'IQ'],
			['nome'=>'Irlanda', 'gentilico'=>'irlandesa', 'sigla'=>'IRL', 'sigla_web'=>'IE'],
			['nome'=>'Islândia', 'gentilico'=>'islandesa', 'sigla'=>'ISL', 'sigla_web'=>'IS'],
			['nome'=>'Israel', 'gentilico'=>'israelense', 'sigla'=>'ISR', 'sigla_web'=>'IL'],
			['nome'=>'Itália', 'gentilico'=>'italiana', 'sigla'=>'ITA', 'sigla_web'=>'IT'],
			['nome'=>'Jamaica', 'gentilico'=>'jamaicana', 'sigla'=>'JAM', 'sigla_web'=>'JM'],
			['nome'=>'Japão', 'gentilico'=>'japonesa', 'sigla'=>'JPN', 'sigla_web'=>'JP'],
			['nome'=>'Jersey', 'gentilico'=>'canalina', 'sigla'=>'JEY', 'sigla_web'=>'JE'],
			['nome'=>'Jordânia', 'gentilico'=>'jordaniana', 'sigla'=>'JOR', 'sigla_web'=>'JO'],
			['nome'=>'Kênia', 'gentilico'=>'queniano', 'sigla'=>'KEN', 'sigla_web'=>'KE'],
			['nome'=>'Kiribati', 'gentilico'=>'kiribatiana', 'sigla'=>'KIR', 'sigla_web'=>'KI'],
			['nome'=>'Kuait', 'gentilico'=>'kuwaitiano', 'sigla'=>'KWT', 'sigla_web'=>'KW'],
			['nome'=>'Laos', 'gentilico'=>'laosiana', 'sigla'=>'LAO', 'sigla_web'=>'LA'],
			['nome'=>'Látvia', 'gentilico'=>'letão', 'sigla'=>'LVA', 'sigla_web'=>'LV'],
			['nome'=>'Lesoto', 'gentilico'=>'lesota', 'sigla'=>'LSO', 'sigla_web'=>'LS'],
			['nome'=>'Líbano', 'gentilico'=>'libanesa', 'sigla'=>'LBN', 'sigla_web'=>'LB'],
			['nome'=>'Libéria', 'gentilico'=>'liberiana', 'sigla'=>'LBR', 'sigla_web'=>'LR'],
			['nome'=>'Líbia', 'gentilico'=>'líbia', 'sigla'=>'LBY', 'sigla_web'=>'LY'],
			['nome'=>'Liechtenstein', 'gentilico'=>'liechtensteiniense', 'sigla'=>'LIE', 'sigla_web'=>'LI'],
			['nome'=>'Lituânia', 'gentilico'=>'lituana', 'sigla'=>'LTU', 'sigla_web'=>'LT'],
			['nome'=>'Luxemburgo', 'gentilico'=>'luxemburguesa', 'sigla'=>'LUX', 'sigla_web'=>'LU'],
			['nome'=>'Macau', 'gentilico'=>'macauense', 'sigla'=>'MAC', 'sigla_web'=>'MO'],
			['nome'=>'Macedônia (República Yugoslava)', 'gentilico'=>'macedônio', 'sigla'=>'MKD', 'sigla_web'=>'MK'],
			['nome'=>'Madagascar', 'gentilico'=>'malgaxe', 'sigla'=>'MDG', 'sigla_web'=>'MG'],
			['nome'=>'Malásia', 'gentilico'=>'malaia', 'sigla'=>'MYS', 'sigla_web'=>'MY'],
			['nome'=>'Malaui', 'gentilico'=>'malauiano', 'sigla'=>'MWI', 'sigla_web'=>'MW'],
			['nome'=>'Maldivas', 'gentilico'=>'maldívia', 'sigla'=>'MDV', 'sigla_web'=>'MV'],
			['nome'=>'Mali', 'gentilico'=>'malinesa', 'sigla'=>'MLI', 'sigla_web'=>'ML'],
			['nome'=>'Malta', 'gentilico'=>'maltesa', 'sigla'=>'MLT', 'sigla_web'=>'MT'],
			['nome'=>'Marrocos', 'gentilico'=>'marroquina', 'sigla'=>'MAR', 'sigla_web'=>'MA'],
			['nome'=>'Martinica', 'gentilico'=>'martiniquense', 'sigla'=>'MTQ', 'sigla_web'=>'MQ'],
			['nome'=>'Maurício', 'gentilico'=>'mauriciana', 'sigla'=>'MUS', 'sigla_web'=>'MU'],
			['nome'=>'Mauritânia', 'gentilico'=>'mauritana', 'sigla'=>'MRT', 'sigla_web'=>'MR'],
			['nome'=>'Mayotte', 'gentilico'=>'maiotense', 'sigla'=>'MYT', 'sigla_web'=>'YT'],
			['nome'=>'México', 'gentilico'=>'mexicana', 'sigla'=>'MEX', 'sigla_web'=>'MX'],
			['nome'=>'Micronésia', 'gentilico'=>'micronésia', 'sigla'=>'FSM', 'sigla_web'=>'FM'],
			['nome'=>'Moçambique', 'gentilico'=>'moçambicana', 'sigla'=>'MOZ', 'sigla_web'=>'MZ'],
			['nome'=>'Moldova', 'gentilico'=>'moldavo', 'sigla'=>'MDA', 'sigla_web'=>'MD'],
			['nome'=>'Mônaco', 'gentilico'=>'monegasca', 'sigla'=>'MCO', 'sigla_web'=>'MC'],
			['nome'=>'Mongólia', 'gentilico'=>'mongol', 'sigla'=>'MNG', 'sigla_web'=>'MN'],
			['nome'=>'Montenegro', 'gentilico'=>'montenegra', 'sigla'=>'MNE', 'sigla_web'=>'ME'],
			['nome'=>'Montserrat', 'gentilico'=>'montserratiano', 'sigla'=>'MSR', 'sigla_web'=>'MS'],
			['nome'=>'Myanma', 'gentilico'=>'birmanês', 'sigla'=>'MMR', 'sigla_web'=>'MM'],
			['nome'=>'Namíbia', 'gentilico'=>'namíbia', 'sigla'=>'NAM', 'sigla_web'=>'NA'],
			['nome'=>'Nauru', 'gentilico'=>'nauruana', 'sigla'=>'NRU', 'sigla_web'=>'NR'],
			['nome'=>'Nepal', 'gentilico'=>'nepalesa', 'sigla'=>'NPL', 'sigla_web'=>'NP'],
			['nome'=>'Nicarágua', 'gentilico'=>'nicaraguense', 'sigla'=>'NIC', 'sigla_web'=>'NI'],
			['nome'=>'Níger', 'gentilico'=>'nigerina', 'sigla'=>'NER', 'sigla_web'=>'NE'],
			['nome'=>'Nigéria', 'gentilico'=>'nigeriana', 'sigla'=>'NGA', 'sigla_web'=>'NG'],
			['nome'=>'Niue', 'gentilico'=>'niueana', 'sigla'=>'NIU', 'sigla_web'=>'NU'],
			['nome'=>'Noruega', 'gentilico'=>'norueguesa', 'sigla'=>'NOR', 'sigla_web'=>'NO'],
			['nome'=>'Nova Caledônia', 'gentilico'=>'caledônia', 'sigla'=>'NCL', 'sigla_web'=>'NC'],
			['nome'=>'Nova Zelândia', 'gentilico'=>'neozelandesa', 'sigla'=>'NZL', 'sigla_web'=>'NZ'],
			['nome'=>'Omã', 'gentilico'=>'omani', 'sigla'=>'OMN', 'sigla_web'=>'OM'],
			['nome'=>'Palau', 'gentilico'=>'palauense', 'sigla'=>'PLW', 'sigla_web'=>'PW'],
			['nome'=>'Panamá', 'gentilico'=>'zona do canal do panamá', 'sigla'=>'PAN', 'sigla_web'=>'PA'],
			['nome'=>'Papua-Nova Guiné', 'gentilico'=>'pauásia', 'sigla'=>'PNG', 'sigla_web'=>'PG'],
			['nome'=>'Paquistão', 'gentilico'=>'paquistanesa', 'sigla'=>'PAK', 'sigla_web'=>'PK'],
			['nome'=>'Paraguai', 'gentilico'=>'paraguaia', 'sigla'=>'PRY', 'sigla_web'=>'PY'],
			['nome'=>'Peru', 'gentilico'=>'peruana', 'sigla'=>'PER', 'sigla_web'=>'PE'],
			['nome'=>'Polinésia Francesa', 'gentilico'=>'franco-polinésia', 'sigla'=>'PYF', 'sigla_web'=>'PF'],
			['nome'=>'Polônia', 'gentilico'=>'polonesa', 'sigla'=>'POL', 'sigla_web'=>'PL'],
			['nome'=>'Porto Rico', 'gentilico'=>'portorriquenha', 'sigla'=>'PRI', 'sigla_web'=>'PR'],
			['nome'=>'Portugal', 'gentilico'=>'portuguesa', 'sigla'=>'PRT', 'sigla_web'=>'PT'],
			['nome'=>'Qatar', 'gentilico'=>'catarense', 'sigla'=>'QAT', 'sigla_web'=>'QA'],
			['nome'=>'Quirguistão', 'gentilico'=>'quirguiz', 'sigla'=>'KGZ', 'sigla_web'=>'KG'],
			['nome'=>'República Centro-Africana', 'gentilico'=>'centro-africana', 'sigla'=>'CAF', 'sigla_web'=>'CF'],
			['nome'=>'República Democrática do Congo', 'gentilico'=>'congolesa', 'sigla'=>'COD', 'sigla_web'=>'CD'],
			['nome'=>'República Dominicana', 'gentilico'=>'dominicana', 'sigla'=>'DOM', 'sigla_web'=>'DO'],
			['nome'=>'República Tcheca', 'gentilico'=>'tcheco', 'sigla'=>'CZE', 'sigla_web'=>'CZ'],
			['nome'=>'Romênia', 'gentilico'=>'romena', 'sigla'=>'ROM', 'sigla_web'=>'RO'],
			['nome'=>'Ruanda', 'gentilico'=>'ruandesa', 'sigla'=>'RWA', 'sigla_web'=>'RW'],
			['nome'=>'Rússia', 'gentilico'=>'russa', 'sigla'=>'RUS', 'sigla_web'=>'RU'],
			['nome'=>'Saara Ocidental', 'gentilico'=>'saariano', 'sigla'=>'ESH', 'sigla_web'=>'EH'],
			['nome'=>'Saint Vincente e Granadinas', 'gentilico'=>'sao-vicentino', 'sigla'=>'VCT', 'sigla_web'=>'VC'],
			['nome'=>'Samoa Americana', 'gentilico'=>'samoana', 'sigla'=>'ASM', 'sigla_web'=>'AS'],
			['nome'=>'Samoa Ocidental', 'gentilico'=>'samoano', 'sigla'=>'WSM', 'sigla_web'=>'WS'],
			['nome'=>'San Marino', 'gentilico'=>'samarinês', 'sigla'=>'SMR', 'sigla_web'=>'SM'],
			['nome'=>'Santa Helena', 'gentilico'=>'helenense', 'sigla'=>'SHN', 'sigla_web'=>'SH'],
			['nome'=>'Santa Lúcia', 'gentilico'=>'santa-lucense', 'sigla'=>'LCA', 'sigla_web'=>'LC'],
			['nome'=>'São Bartolomeu', 'gentilico'=>'são-bartolomeense', 'sigla'=>'BLM', 'sigla_web'=>'BL'],
			['nome'=>'São Cristóvão e Névis', 'gentilico'=>'são-cristovense', 'sigla'=>'KNA', 'sigla_web'=>'KN'],
			['nome'=>'São Martim', 'gentilico'=>'são-martinhense', 'sigla'=>'MAF', 'sigla_web'=>'MF'],
			['nome'=>'São Tomé e Príncipe', 'gentilico'=>'são-tomense', 'sigla'=>'STP', 'sigla_web'=>'ST'],
			['nome'=>'Senegal', 'gentilico'=>'senegalesa', 'sigla'=>'SEN', 'sigla_web'=>'SN'],
			['nome'=>'Serra Leoa', 'gentilico'=>'leonesa', 'sigla'=>'SLE', 'sigla_web'=>'SL'],
			['nome'=>'Sérvia', 'gentilico'=>'sérvia', 'sigla'=>'SRB', 'sigla_web'=>'RS'],
			['nome'=>'Síria', 'gentilico'=>'síria', 'sigla'=>'SYR', 'sigla_web'=>'SY'],
			['nome'=>'Somália', 'gentilico'=>'somali', 'sigla'=>'SOM', 'sigla_web'=>'SO'],
			['nome'=>'Sri Lanka', 'gentilico'=>'cingalesa', 'sigla'=>'LKA', 'sigla_web'=>'LK'],
			['nome'=>'St. Pierre and Miquelon', 'gentilico'=>'pedro-miquelonense', 'sigla'=>'SPM', 'sigla_web'=>'PM'],
			['nome'=>'Suazilândia', 'gentilico'=>'suazi', 'sigla'=>'SWZ', 'sigla_web'=>'SZ'],
			['nome'=>'Sudão', 'gentilico'=>'sudanesa', 'sigla'=>'SDN', 'sigla_web'=>'SD'],
			['nome'=>'Suécia', 'gentilico'=>'sueca', 'sigla'=>'SWE', 'sigla_web'=>'SE'],
			['nome'=>'Suíça', 'gentilico'=>'suíça', 'sigla'=>'CHE', 'sigla_web'=>'CH'],
			['nome'=>'Suriname', 'gentilico'=>'surinamesa', 'sigla'=>'SUR', 'sigla_web'=>'SR'],
			['nome'=>'Tadjiquistão', 'gentilico'=>'tadjique', 'sigla'=>'TJK', 'sigla_web'=>'TJ'],
			['nome'=>'Tailândia', 'gentilico'=>'tailandesa', 'sigla'=>'THA', 'sigla_web'=>'TH'],
			['nome'=>'Taiwan', 'gentilico'=>'taiwanês', 'sigla'=>'TWN', 'sigla_web'=>'TW'],
			['nome'=>'Tanzânia', 'gentilico'=>'tanzaniana', 'sigla'=>'TZA', 'sigla_web'=>'TZ'],
			['nome'=>'Território Britânico do Oceano índico', 'gentilico'=>'do território britânico do oceano índico', 'sigla'=>'IOT', 'sigla_web'=>'IO'],
			['nome'=>'Territórios do Sul da França', 'gentilico'=>'do territórios do sul da frança', 'sigla'=>'ATF', 'sigla_web'=>'TF'],
			['nome'=>'Territórios Palestinos Ocupados', 'gentilico'=>'palestino', 'sigla'=>'PSE', 'sigla_web'=>'PS'],
			['nome'=>'Timor Leste', 'gentilico'=>'', 'sigla'=>'TMP', 'sigla_web'=>'TP'],
			['nome'=>'Togo', 'gentilico'=>'togolesa', 'sigla'=>'TGO', 'sigla_web'=>'TG'],
			['nome'=>'Tonga', 'gentilico'=>'tonganesa', 'sigla'=>'TON', 'sigla_web'=>'TO'],
			['nome'=>'Trinidad and Tobago', 'gentilico'=>'trinitário-tobagense', 'sigla'=>'TTO', 'sigla_web'=>'TT'],
			['nome'=>'Tunísia', 'gentilico'=>'tunisiana', 'sigla'=>'TUN', 'sigla_web'=>'TN'],
			['nome'=>'Turcomenistão', 'gentilico'=>'turcomana', 'sigla'=>'TKM', 'sigla_web'=>'TM'],
			['nome'=>'Turquia', 'gentilico'=>'turca', 'sigla'=>'TUR', 'sigla_web'=>'TR'],
			['nome'=>'Tuvalu', 'gentilico'=>'tuvaluana', 'sigla'=>'TUV', 'sigla_web'=>'TV'],
			['nome'=>'Ucrânia', 'gentilico'=>'ucraniana', 'sigla'=>'UKR', 'sigla_web'=>'UA'],
			['nome'=>'Uganda', 'gentilico'=>'ugandense', 'sigla'=>'UGA', 'sigla_web'=>'UG'],
			['nome'=>'Uruguai', 'gentilico'=>'uruguaia', 'sigla'=>'URY', 'sigla_web'=>'UY'],
			['nome'=>'Uzbequistão', 'gentilico'=>'uzbeque', 'sigla'=>'UZB', 'sigla_web'=>'UZ'],
			['nome'=>'Vanuatu', 'gentilico'=>'vanuatuense', 'sigla'=>'VUT', 'sigla_web'=>'VU'],
			['nome'=>'Vaticano', 'gentilico'=>'vaticano', 'sigla'=>'VAT', 'sigla_web'=>'VA'],
			['nome'=>'Venezuela', 'gentilico'=>'venezuelana', 'sigla'=>'VEN', 'sigla_web'=>'VE'],
			['nome'=>'Vietnã', 'gentilico'=>'vietnamita', 'sigla'=>'VNM', 'sigla_web'=>'VN'],
			['nome'=>'Zâmbia', 'gentilico'=>'zambiana', 'sigla'=>'ZMB', 'sigla_web'=>'ZM'],
			['nome'=>'Zimbábue', 'gentilico'=>'zimbabuana', 'sigla'=>'ZWE', 'sigla_web'=>'ZW']
		]);

		DB::table('perfil')->insert([
            ['descricao' => 'Administrador', 'administrador' => true],

        ]);
        /*
		DB::table('usuario')->insert([
        	'nome' => 'Admin',
            'nome_completo' => 'Administrador do Sistema',
            'email' => 'admin@gmail.com',
            'login' => 'admin',
            'senha' => md5('senha'),
            'perfil_id' => 1,
            'pais_id' => 31,
            'estado_civil_id' => 1,
        ]);
		

		DB::table('usuario')->insert([
            [
            	'nome' => 'Juvenal',
	            'nome_completo' => 'Juvenal da Silva',
	            'email' => 'juvenal@gmail.com',
	            'sexo' => 'M',
	            'login' => 'juvenal',
	            'senha' => md5('senha'),
	            'perfil_id' => 2,
	            'pais_id' => 31,
	            'estado_civil_id' => rand(1, 5),
	        ],
            [
            	'nome' => 'Maria',
	            'nome_completo' => 'Maria José de Jesus',
	            'email' => 'mariajose@gmail.com',
	            'sexo' => 'F',
	            'login' => 'maria',
	            'senha' => md5('senha'),
	            'perfil_id' => 2,
	            'pais_id' => 31,
	            'estado_civil_id' => rand(1, 5),
	        ],
            [
            	'nome' => 'Joaquim',
	            'nome_completo' => 'Joaquim de Souza',
	            'email' => 'joaquim@gmail.com',
	            'sexo' => 'M',
	            'login' => 'joaquim',
	            'senha' => md5('senha'),
	            'perfil_id' => 2,
	            'pais_id' => 31,
	            'estado_civil_id' => rand(1, 5),
	        ],
            [
            	'nome' => 'Marinalva',
	            'nome_completo' => 'Marinalva Duarte',
	            'email' => 'marinalva@gmail.com',
	            'sexo' => 'F',
	            'login' => 'marinalva',
	            'senha' => md5('senha'),
	            'perfil_id' => 2,
	            'pais_id' => 31,
	            'estado_civil_id' => rand(1, 5),
	        ],
        ]);

        */
    }
}

//factory(App\Perfil::class, 1)->create();
//factory(App\User::class, 10)->create();